# CrashDetectorwithAI Configuration
# You can specify absolute paths with regular backslashes
# Example: C:\Path\To\Model

# Path to the Phi-4 model
modelPath: C:\Path\To\Model\Phi4\phi-4-onnx\cpu_and_mobile\cpu-int4-rtn-block-32-acc-level-4
